name: animations_sample
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  cupertino_icons: ^1.0.2
  fl_chart: ^0.40.2
  funvas: ^0.1.3
  fps_widget: ^1.0.1+1
  gap: ^2.0.0
  google_fonts: ^2.0.0
  line_icons: ^2.0.1
  provider: ^6.0.1
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0
  build_web_compilers: ^3.2.1
  build_runner: ^2.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/
